import type { Metadata } from "next";
import PageHero from "@/components/PageHero";
import LegalSection from "@/components/LegalSection";

export const metadata: Metadata = {
  title: "Privacy Policy — QuickCarry",
  description:
    "How QuickCarry collects, uses, and protects your personal information, effective May 1, 2026.",
};

const EFFECTIVE_DATE = "May 1, 2026";

const sections: {
  title: string;
  paragraphs: string[];
  list?: string[];
}[] = [
  {
    title: "Introduction",
    paragraphs: [
      "This Privacy Policy explains how QuickCarry collects, uses, shares, and protects personal information when you use our website, app, and delivery services. It applies to customers, riders, and business account holders alike.",
      "QuickCarry processes personal data in line with the Nigeria Data Protection Act, 2023 (NDPA) and its implementing regulations.",
    ],
  },
  {
    title: "Information we collect",
    paragraphs: [
      "We collect information you provide directly, information generated by using the Service, and information from third parties involved in fulfilling a delivery.",
    ],
    list: [
      "Identity and contact details: name, phone number, email address, and delivery addresses",
      "Location data: pickup, drop-off, and live rider location while a delivery is in progress",
      "Payment information: processed by our payment partners; QuickCarry does not store full card numbers",
      "Order and wallet activity: delivery history, Business Wallet balance and transactions, cashback and referral activity",
      "Photos: pickup and drop-off verification photos taken by riders and merchants",
      "Device and usage data: app version, device type, and general usage analytics",
    ],
  },
  {
    title: "How we use your information",
    paragraphs: [
      "We use personal data to operate the Service and for legitimate business purposes connected to it.",
    ],
    list: [
      "Matching delivery requests with available riders and calculating pricing",
      "Verifying pickup and delivery, and resolving Delivery Insurance claims",
      "Processing payments, wallet top-ups, and cashback",
      "Customer support and responding to enquiries",
      "Fraud prevention and platform safety",
      "Sending service updates, receipts, and — where you've opted in — product announcements",
    ],
  },
  {
    title: "Who we share information with",
    paragraphs: [
      "We share personal data only where necessary to provide the Service, and never sell your personal information.",
    ],
    list: [
      "Riders and merchants involved in fulfilling your specific delivery, limited to what's needed to complete it",
      "Payment processors, to process transactions and wallet top-ups",
      "Service providers who support our infrastructure, such as hosting and customer support tooling",
      "Law enforcement or regulators, where required by Nigerian law",
    ],
  },
  {
    title: "Data retention",
    paragraphs: [
      "We retain personal data for as long as your account is active and for a reasonable period afterward to meet legal, accounting, and dispute-resolution obligations, after which it is deleted or anonymized.",
    ],
  },
  {
    title: "Data security",
    paragraphs: [
      "We apply administrative, technical, and physical safeguards designed to protect personal data against unauthorized access, alteration, or loss, including encryption of payment data in transit and access controls on internal systems. No method of transmission or storage is completely secure, and we can't guarantee absolute security.",
    ],
  },
  {
    title: "Your rights",
    paragraphs: [
      "Under the NDPA, you have rights over your personal data, which you can exercise by contacting us using the details below.",
    ],
    list: [
      "Access the personal data we hold about you",
      "Correct inaccurate or incomplete data",
      "Request deletion of your data, subject to legal retention requirements",
      "Withdraw consent to marketing communications at any time",
      "Object to certain processing of your data",
    ],
  },
  {
    title: "Cookies and tracking",
    paragraphs: [
      "Our website and app use cookies and similar technologies to keep you signed in, remember preferences, and understand how the Service is used. You can control cookies through your browser settings; disabling them may affect parts of the Service.",
    ],
  },
  {
    title: "Children's privacy",
    paragraphs: [
      "QuickCarry is not directed at children under 18, and we don't knowingly collect personal data from them. If you believe a child has provided us with personal data, contact us and we'll delete it.",
    ],
  },
  {
    title: "Changes to this policy",
    paragraphs: [
      "We may update this Privacy Policy as our services evolve. We'll post the revised policy with an updated effective date, and material changes will be communicated in-app or by email ahead of taking effect.",
    ],
  },
  {
    title: "Contact us",
    paragraphs: [
      "For privacy questions or to exercise your rights under the NDPA, contact us at hello@quickcarry.ng or +234 803 365 1598.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <>
      <PageHero
        eyebrow="Legal"
        title="Privacy Policy"
        description={`Effective ${EFFECTIVE_DATE}`}
      />
      <section className="bg-cream py-20 sm:py-28">
        <div className="mx-auto max-w-3xl px-6 lg:px-8">
          {sections.map((section, i) => (
            <LegalSection key={section.title} index={i + 1} {...section} />
          ))}
        </div>
      </section>
    </>
  );
}
